# Generated by Django 4.2.30 on 2026-10-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
