# Generated by Django 4.2.30 on 2026-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('publication_year', models.IntegerField(verbose_name='Год публикаци')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательство')),
                ('is_available', models.BooleanField(verbose_name='Доступна ли книга в продаже')),
            ],
        ),
    ]
